[package]
name = "rust_auth_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2.22", features = ["full"] }
warp = "0.3.7"
